# Env file for reading by docker to know where secrets are stored
# remote_env_file: /tmp/.env
# Path for cert-FILE locally and on vm(same path)
sa_certificate_key_file: "{{ secret_ops_dir }}/yc_cert_downloader_sa_key.json"
consul_template_upstream: "/consul-template/output/upstream.conf"
nginx_upstream_dir: "/etc/nginx/conf.d/upstream.conf"
# Path for cert-DIR inside container