openapi: 3.0.0
info:
  title: Serverless API Gateway
  version: 1.0.0

paths:
  /all:
    get:
      summary: Combined user and orders
      x-yc-apigateway-integration:
        type: combine
        combine:
          - id: name
            request:
              http:
                url: http://service_name.internal/api/name     # internal dns name not public
          - id: object
            request:
              http:
                url: http://service_object.internal/api/object

          - id: color
            request:
              http:
                url: http://service_color.internal/api/color
        response:
          mapping:
            name: $responses.name.body
            object: $responses.object.body
            color: $responses.color.body