---
- name: Build frontend static (npm run build)
  shell: |
    npm ci
    npm run build
  args:
    chdir: "{{ frontend_build_path }}"
  delegate_to: localhost

- name: Copy frontend build to docker context
  copy:
    src: "{{ frontend_build_path }}/build/"
    dest: "{{ docker_build_path }}/build/"
    mode: '0644'
  delegate_to: localhost