consul_template_version: "0.40.0"
consul_template_template_path: "/etc/consul-template/upstream.conf.ctmpl"
consul_template_output_path: "/consul-template/output/upstream.conf"
consul_template_reload_command: "docker exec nginx_container sh -c 'nginx -t && nginx -s reload'"