# use_subservice_infra: false

---
- name: Deploy fastapi backend
  hosts: all
  become: true
  vars:
    consul_server_group: "env_dev__app_autoscale__service_nginx" # where consul_server is located
  roles:
    - docker_install
    - consul_server