# # use_subservice_infra: false

# # Avoid marking deploy_status=true without consul_server to be deployed
# ---
# - name: Deploy fastapi backend
#   hosts: all
#   become: true
#   vars:
#     consul_server_group: "env_dev__app_soa__service_nginx"                                    # where consul_server is located
#   roles:
#     - docker_install
#     - role: consul_agent
#       vars:
#         consul_service_port: 8000                                                             # uvicorn/fastapi port instead of consul
#         consul_check_http: "http://localhost:{{ consul_service_port }}/health"
#     - fastapi
#     - consul_dns_enable
#     - save_successful_hosts

